default['mongodb'] = {}
default['mongodb']['version'] = '2.4.9'
default['mongodb']['package_basename'] = "mongodb-linux-#{node['kernel']['machine']}-#{node['mongodb']['version']}"
default['mongodb']['package_filename'] = "#{node['mongodb']['package_basename']}.tgz"
default['mongodb']['prefix'] = '/opt'
default['mongodb']['basedir'] = ::File.join(node['mongodb']['prefix'], "mongodb-#{node['kernel']['machine']}-#{node['mongodb']['version']}")
default['mongodb']['bindir'] = ::File.join(node['mongodb']['basedir'], 'bin')
default['mongodb']['confdir'] = ::File.join(node['mongodb']['basedir'], 'conf')
default['mongodb']['conffile'] = 'mongodb.conf'
default['mongodb']['conf_filename'] = ::File.join(node['mongodb']['confdir'], node['mongodb']['conffile'])
default['mongodb']['user'] = 'mongodb'
default['mongodb']['group'] = 'mongodb'
default['mongodb']['dbpath'] = '/vol/data'
default['mongodb']['logdir'] = '/vol/log'
default['mongodb']['logfile'] = 'mongodb.log'
default['mongodb']['log_filename'] = ::File.join(node['mongodb']['logdir'], node['mongodb']['logfile'])
default['mongodb']['logappend'] = true
default['mongodb']['bind_ip'] = '127.0.0.1'
default['mongodb']['port'] = '27017'
default['mongodb']['rest'] = true
default['mongodb']['journal'] = true
